DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS flokkur;
DROP TABLE IF EXISTS vorur;
DROP TABLE IF EXISTS karfa;
DROP TABLE IF EXISTS linurkorfu;
DROP TABLE IF EXISTS pontun;
DROP TABLE IF EXISTS linurpontun;
DROP TABLE IF EXISTS stadapontun;